### ISSUE TITLE
how to avoid nsfw content 

### ISSUE THREAD

**Issue by zortos293** [pevers/images-scraper#60]
i want to turn of nsfw content so that it doesn't  popup on discord how can i do that

**Comment by pevers** [comment]
It is currently not supported. But I'm open for pull requests.

A naive approach would be "clicking" the toggle in the mainscreen via the headless browser.

**Comment by MarceloBrazolim** [comment]
for a quick fix you could just add "&safe=active" in the searchQuery since there is no formating or treatment at https://github.com/pevers/images-scraper/blob/master/src/google/scraper.js line 42
![Screenshot_8](https://user-images.githubusercontent.com/22665661/111241518-1665c600-85dc-11eb-9e86-6c82e692d15b.png)

for a future version it could be solved with (I already tested and it works just fine)
```js
constructor({
    safe = false,
  } = {}) {
    this.safe = this._isQuerySafe(safe);
  }

_isQuerySafe(safe) {
  if (safe === true) {
    return '&safe=active';
  } else return '';
}

async scrape(searchQuery, limit = 100) {
  const query = `https://www.google.com/search?q=${searchQuery}&source=lnms&tbm=isch${this.safe}&sa=X&tbs=${this.tbs}`;
}
```

I already made a pull request with this alterations.

also, why is there a "Logger.info()" below the definition of the query variable? it just floods my console since i like to use a customized console and it ruins the flow :v
![Screenshot_9](https://user-images.githubusercontent.com/22665661/111244533-e28d9f00-85e1-11eb-95d4-d2d1dd346949.png)

**Comment by pevers** [comment]
> for a quick fix you could just add "&safe=active" in the searchQuery since there is no formating or treatment at [line 42](https://github.com/pevers/images-scraper/blob/master/src/google/scraper.js)
> ![Screenshot_8](https://user-images.githubusercontent.com/22665661/111241518-1665c600-85dc-11eb-9e86-6c82e692d15b.png)
> 
> ### I already made a pull request with [these alterations](https://github.com/pevers/images-scraper/pull/64).
> for a future version it could be solved with this (I already tested and it works just fine):
> 
> ```js
> constructor({
>     safe = false,
>   } = {}) {
>     this.safe = this._isQuerySafe(safe);
>   }
> 
> _isQuerySafe(safe) {
>   if (safe === true) {
>     return '&safe=active';
>   } else return '';
> }
> 
> async scrape(searchQuery, limit = 100) {
>   const query = `https://www.google.com/search?q=${searchQuery}&source=lnms&tbm=isch${this.safe}&sa=X&tbs=${this.tbs}`;
> }
> ```
> 

Thanks! This indeed solves it! I've merged it and I'll create a new release.

> also, why is there a "Logger.info()" below the definition of the query variable? it just floods my console since i like to use a customized console and it ruins the flow :v
> ![Screenshot_9](https://user-images.githubusercontent.com/22665661/111244533-e28d9f00-85e1-11eb-95d4-d2d1dd346949.png)

This is a mistake. I'll fix it. Thanks for reporting

**Comment by pevers** [comment]
I'm closing this. Feature added in 6.1
